units:
  kx: cx
  ky: cy
  px: 2
  py: 2
  ring_rotate: -20
points:
  key:
    footprints:
      choc:
        type: choc
        anchor:
          rotate: 180
        nets:
          from: =column_net
          to: =colrow
        params:
          keycaps: true
          reverse: false
      diode:
        type: diode
        anchor:
          shift: [0, -8.5]
          rotate: 180
        nets:
          from: =colrow
          to: =row_net

  zones:
    matrix:
      rotate: -15
      mirror: &mirror
        ref: matrix_inner_bottom
        shift: [0, -U]
        distance: 4.25U
      columns:
        pinkycluster:
          origin: [ 0, 1cy ]
          rotate: 0
          key:
            column_net: P21
            mirror.column_net: P21
        pinky:
          rotate: 0
          stagger: 4
          spread: cx
          origin: [ 0, -1cy ]
          key:
            column_net: P20
            mirror.column_net: P20
        ring:
          rotate: 0
          stagger: 8.8
          spread: cx
          key:
            column_net: P19
            mirror.column_net: P19
        middle:
          origin: [ 0, -1cy ]
          rotate: 0
          stagger: 4.7
          spread: cx
          key:
            column_net: P18
            mirror.column_net: P18
        index:
          origin: [ 0, -1cy ]
          rotate: 0
          stagger: -4.7
          spread: cx
          key:
            column_net: P15
            mirror.column_net: P15
        inner:
          origin: [ 0, -1cy ]
          rotate: 0
          spread: cx
          stagger: -3
          key:
            column_net: P14
            mirror.column_net: P14
      rows:
        bottom:
          padding: 1ky
          row_net: P6
          mirror.row_net: P6
          mirror:
            footprints:
              diode:
                anchor:
                  rotate: 0
          
        home:
          padding: 1ky
          row_net: P7
          mirror.row_net: P7
          mirror:
            footprints:
              diode:
                anchor:
                  rotate: 0
        top:
          padding: 1ky
          row_net: P8
          mirror.row_net: P8
          mirror:
            footprints:
              diode: &diode
                anchor:
                  rotate: 0
              diode2: 
                type: diode
                anchor: 
                  shift: [0, 8.5]
                nets:
                  from: =column_net
                  to: =column_net
    trackball_under:
      mirror: &mirror_tb
        ref: matrix_inner_bottom
        shift: [0, -U]
        distance: 4.25U
      anchor:
        ref: matrix_inner_bottom
        shift: [ 15.5, -18 ]
      columns:
        only:
          origin: [-cx/2, -cy/2]
          stagger: 5.64
          spread: -3.04
          rotate: -30
          key:
            column_net: P5
            mirror.column_net: P16
            column_mark: TBM
      rows:
        only:
          padding: 0
          row_net: P9
          footprints:
            diode:
              anchor:
                shift: [0, 8.5]
          mirror:
            footprints:
              diode:
                anchor:
                  rotate: 0
          
         
      
    thumbfan:
      mirror: &mirror
        ref: matrix_inner_bottom
        shift: [0, -U]
        distance: 4.25U
      anchor:
        ref: matrix_inner_bottom
        shift: [ 17.5, -40 ]
      columns:
        right:
          origin: [-cx/2, -cy/2]
          stagger: 5.64
          spread: -3.04
          rotate: -30
          key:
            column_net: P5
            mirror.column_net: P16
            column_mark: R
        middle:
          origin: [-cx/2, -cy/2]
          rotate: 15
          stagger: -4.72
          spread: -1.5cx + 0.27
          key:
            column_net: P4
            mirror.column_net: P17
            column_mark: M
        left:
          origin: [-cx/2, -cy/2]
          stagger: -4.4
          spread: -cx + 0.6
          rotate: 14
          key:
            column_net: P3
            mirror.column_net: P18
            column_mark: P
        lefter:
          origin: [-cx/2, -cy/2]
          stagger: -0
          spread: -cx + 0
          rotate: 0
          key:
            column_net: P3
            mirror.column_net: P18
            column_mark: P
      rows:
        thumb:
          padding: 0
          row_net: P9
          footprints:
            diode:
              anchor:
                shift: [0, 8.5]
          mirror:
            footprints:
              diode:
                anchor:
                  rotate: 0
          


outlines:
  glue:
    default:
      top:
        left:
          ref: matrix_inner_top
          shift: [0.5, 7]
        right:
          ref: mirror_matrix_inner_top
          shift: [0.5, 7]
      bottom:
        left:
          ref: matrix_inner_bottom
          #thumbfan_home_thumb
          shift: [0.5, -0.5]
        right:
          ref: mirror_matrix_inner_bottom
          #mirror_thumbfan_home_thumb
          shift: [0.5, -0.5]
  exports:
    raw:
      - type: keys
        side: both
        size: [kx, ky]
        corner: px
    top_arc_left_intersect:
      - type: polygon
        points:
          - ref: matrix_pinkycluster_top
            shift: [-px-cx/2, py+cy/2]
          - ref: matrix_middle_top
            shift: [cx/2, cy/2]
          - ref: matrix_middle_top
            shift: [cx/2, 2cy]
          - ref: matrix_pinkycluster_top
            shift: [-px-cx/2, py+3cy]
    mirror_top_arc_left_intersect:
      - type: polygon
        points:
          - ref: mirror_matrix_pinkycluster_top
            shift: [-px-cx/2, py+cy/2]
          - ref: mirror_matrix_middle_top
            shift: [cx/2, cy/2]
          - ref: mirror_matrix_middle_top
            shift: [cx/2, 2cy]
          - ref: mirror_matrix_pinkycluster_top
            shift: [-px-cx/2, py+3cy]
    top_arc_right_intersect:
      - type: polygon
        points:
          - ref: matrix_middle_top
            shift: [cx/2, -cy/2]
          - ref: matrix_middle_top
            shift: [cx/2, 2cy]
          - ref: matrix_inner_top
            shift: [cx/2, 3cy]
          - ref: matrix_inner_top
            shift: [cx/2, cy/2]
    mirror_top_arc_right_intersect:
      - type: polygon
        points:
          - ref: mirror_matrix_middle_top
            shift: [cx/2, -cy/2]
          - ref: mirror_matrix_middle_top
            shift: [cx/2, 2cy]
          - ref: mirror_matrix_inner_top
            shift: [cx/2, 3cy]
          - ref: mirror_matrix_inner_top
            shift: [cx/2, cy/2]
    bottom_arc_left_intersect:
      - type: polygon
        points:
          - ref: matrix_pinkycluster_bottom
            shift: [-cx/2, cy/2]
          - ref: matrix_middle_bottom
            shift: [cx/2, cy/2]
          - ref: matrix_middle_bottom
            shift: [cx/2, -4cy]
          - ref: matrix_pinkycluster_bottom
            shift: [-cx/2, -cy]
    bottom_arc_right_intersect:
      - type: polygon
        points:
          - ref: matrix_middle_bottom
            shift: [cx/2, -cy/2]
          - ref: thumbfan_right_thumb
            shift: [cx/2, cy/2]
          - ref: thumbfan_right_thumb
            shift: [cx, -cy/2]
          - ref: thumbfan_right_thumb
            shift: [-2.1cx, -cy]

    arc_top_left: #todo check with top left corner shift
      - type: circle
        anchor:
          ref: matrix_middle_bottom
          shift: [2.2, -24.22]
        radius: 68.7
      - type: outline
        name: top_arc_left_intersect
        operation: intersect
    mirror_arc_top_left: #todo check with top left corner shift
      - type: circle
        anchor:
          ref: mirror_matrix_middle_bottom
          shift: [2.2, -24.22]
        radius: 68.7
      - type: outline
        name: mirror_top_arc_left_intersect
        operation: intersect

    arc_top_right:
      - type: circle
        anchor:
          ref: matrix_middle_bottom
          shift: [-5.58, -99.1]
        radius: 144.02
      - type: outline
        name: top_arc_right_intersect
        operation: intersect
    mirror_arc_top_right:
      - type: circle
        anchor:
          ref: mirror_matrix_middle_bottom
          shift: [-5.58, -99.1]
        radius: 144.02
      - type: outline
        name: mirror_top_arc_right_intersect
        operation: intersect
    arc_bottom_left:
      - type: circle
        anchor:
          ref: matrix_middle_bottom
          shift: [-42.42, -425.95]
        radius: 368.6
      - type: outline
        name: bottom_arc_left_intersect
        operation: intersect
    arc_bottom_right:
      - type: circle
        anchor:
          ref: matrix_middle_bottom
          shift: [-13.3, -205.24]
        radius: 145.98
      - type: outline
        name: bottom_arc_right_intersect
        operation: intersect
    arc_bottom:
      - type: outline
        name: arc_bottom_left
      - type: outline
        name: arc_bottom_right
    sensor_hole: &pwm3360
      - type: rectangle
        anchor:
          ref: [matrix_inner_bottom, mirror_matrix_inner_bottom]
          shift: [-4.275, -10]
        size: [8.55, 21.3]
    pmwscrew_1:
      - type: circle
        radius: 1.25
        anchor:
          ref: [matrix_inner_bottom, mirror_matrix_inner_bottom]
          shift: [-0, 12.75]
    pmwscrew_2:
      - type: circle
        radius: 1.25
        anchor:
          ref: [matrix_inner_bottom, mirror_matrix_inner_bottom]
          shift: [-0, -11.25]

    edge_points:
      - type: polygon
        points:
          - ref: matrix_pinkycluster_top
            shift: [-px-cx/2, cy/2]
          - ref: matrix_ring_top
            shift: [-cx/2, cy/2]
          - ref: matrix_middle_top
            shift: [-cx/2, cy/2]

          - ref: mirror_matrix_middle_top
            shift: [-cx/2, cy/2]
          - ref: mirror_matrix_ring_top
            shift: [-cx/2, cy/2]
          - ref: mirror_matrix_pinkycluster_top
            shift: [-px-cx/2, cy/2]

          - ref: mirror_matrix_pinkycluster_bottom
            shift: [-px-cx/2, -9.5]
          - ref: mirror_thumbfan_lefter_thumb
            shift: [-9.5, -py-cy/2]
          - ref: mirror_thumbfan_left_thumb
            shift: [cx/2, -py-cy/2]
          - ref: mirror_thumbfan_middle_thumb
            shift: [cx/2, -py-cy/2]
          - ref: mirror_thumbfan_right_thumb
            shift: [px+cx/2, -py-cy/2]
          - ref: mirror_thumbfan_right_thumb
            shift: [px+cx/2, py+cy/2]


          - ref: thumbfan_right_thumb
            shift: [px+cx/2, py+cy/2]
          - ref: thumbfan_right_thumb
            shift: [px+cx/2, -py-cy/2]
          - ref: thumbfan_middle_thumb
            shift: [cx/2, -py-cy/2]
          - ref: thumbfan_left_thumb
            shift: [cx/2, -py-cy/2]
          - ref: thumbfan_lefter_thumb
            shift: [-9.5, -py-cy/2]
          
          
          - ref: matrix_pinkycluster_bottom
            shift: [-px-cx/2, -9.5]
          - ref: matrix_pinkycluster_top
            shift: [-px-cx/2, cy/2]
    controller_area:
      main:
        type: rectangle
        anchor:
          ref:
            - matrix_inner_top
          shift: [0, -60.25]
        size: [32, 62.5]
        corner: px
    keycaps:
      main:
        type: keys
        side: both
        size: [kx, ky]
        bound: false
        corner: 1
    trackball:
      center:
        type: circle
        radius: 17.5
        anchor:
          ref: [matrix_inner_bottom, mirror_matrix_inner_bottom]
          shift: [-0, -0]

    base_outline:
      main:
        type: outline
        name: raw
      arc_top_left:
        type: outline
        name: arc_top_left
      mirror_arc_top_left:
        type: outline
        name: mirror_arc_top_left
      arc_top_right:
        type: outline
        name: arc_top_right
      mirror_arc_top_right:
        type: outline
        name: mirror_arc_top_right
      edge:
        type: outline
        name: edge_points
      controller:
        type: outline
        name: controller_area
      arc_bottom_right:
        type: outline
        name: arc_bottom
        operation: subtract
      sensor_hole_cut:
        type: outline
        name: sensor_hole
        operation: subtract
      pmwscrew_1_cut:
        type: outline
        name: pmwscrew_1
        operation: subtract
      pmwscrew_2_cut:
        type: outline
        name: pmwscrew_2
        operation: subtract

    plate:
      main:
        type: outline
        name: base_outline
      switches:
        type: outline
        name: keycaps
        operation: subtract
    pcb:
      main:
        type: outline
        name: base_outline
      trackball:
        type: outline
        name: trackball
        operation: stack

pcbs:
  board:
    outlines:
      edge:
        outline: pcb
        layer: Edge.Cuts
    footprints:
      mcu_l:
        type: promicro
        params:
          orientation: up
        anchor:
          ref: [matrix_inner_top, mirror_matrix_inner_top]
          shift: [0, 6]
          rotate: 270
      reset:
        type: button
        anchor:
          ref: [matrix_inner_top, mirror_matrix_inner_top]
          shift: [15, 19]
          rotate: 0
        params:
          variant: 2_pin_th
        nets:
          from: GND
          to: RST
      scrollwheel:
        type: scrollwheel
        anchor:
          ref: [matrix_inner_bottom, mirror_matrix_inner_bottom]
          shift: [0, -32]
        nets:
          from: undefined
          to: undefined
          A: P4
          B: GND
          C: P5
          D: undefined